### PR TITLE
Add polish translation for Arduino blocks

### PR DESCRIPTION
**Pull request by kkubicki**
Currently there is no polish translation for Arduino blocks. This change adds it to the repository.

### CODE REVIEW

**Comment by jguille2** [comment]
Hi Krzysztof (@kkubicki )

I'm sorry for our no response :(

I saw your last message two weeks ago and noted to see it and test it, before our next minor release...

But now, I see you first PR is from 2020!! I'm sorry.

I was not aware of this request. I'll look into it before I release any new versions to add it.

Thank you and sorry

Joan

**Comment by kkubicki** [comment]
Hi Joan, 

No problem :) I just wasn't sure I made everything to be ready for merge (hence close/reopen action). Anyway, give me word if something is not working, I'll try to fix that.

BR,
Krzysztof

**Comment by jguille2** [comment]
Thanks Krzysztof (@kkubicki )

I will release a minor versions (8.2.3) to track some changes and then, your Polish translation will be there!

Thanks and sorry for the delay.

Joan

**Comment by jguille2** [comment]
And I've added credits for your translation. Thanks

https://github.com/bromagosa/Snap4Arduino/blob/540e273656e94643dce19c1fb8f0a7bbbd665bbd/src/s4a/gui.js#L466

**Comment by jguille2** [comment]
Hi Krzysztof @kkubicki 

Today I've released v8.2.4 with your Polish translation

https://twitter.com/jguille2/status/1660817381051240448

Thanks!

**Pull request merged**
