### PR TITLE
Update lang-gl.js

### PR DESCRIPTION
**Pull request by mbouzada**
Galician translation update

### CODE REVIEW

**Comment by jguille2** [comment]
Moitas Grazas, Miguel @mbouzada !
I will check it and it will be into the next 5.0 release on September.

Joan

**Comment by mbouzada** [comment]
I need to correct two small mistakes:
Line 113, the exclamation opening (¡) should disappear, it should look like this:
        'Conectouse satisfactoriamente unha tarxeta Arduino.\nFeliz prototipaxe!',

**Comment by mbouzada** [comment]
I need to correct one small mistake:
Line 113, the exclamation opening (¡) should disappear, it should look like this:
        'Conectouse satisfactoriamente unha tarxeta Arduino.\nFeliz prototipaxe!',

**Comment by jguille2** [comment]
Don't worry. I'm on holidays... But I'll check this before the 5.0 release.

**Comment by jguille2** [comment]
Thanks Miguel (@mbouzada )

Your Galego update is merged, and [your last change made](https://github.com/bromagosa/Snap4Arduino/commit/970b66ddbbf7dda6162910fa0f42b641abd3662d).

So, next release (next Monday) will have that.

Joan

**Comment by jguille2** [comment]
Hi Miguel (@mbouzada).

Snap4Arduino 5.1 is just released. So your Galego update is ready now!

[https://twitter.com/jguille2/status/1168478642453864449](
https://twitter.com/jguille2/status/1168478642453864449)

Thanks,

Joan

**Pull request merged**
