### PR TITLE
Added SoundScope website URLs to manifest.json in chromium extension

### PR DESCRIPTION
**Pull request by Ericthestein**
Hello. I am a research assistant at the University of Virginia who is working on SoundScope (https://soundscope-website.web.app/), an online learning environment in which users can synthesize music using block coding via Snap! To further augment this environment, we would like for users to be able to connect to their Arduino boards and program unique playback effects (such as lights turning on/off in sync with the music that is currently playing and being displayed on a graph). We are also considering training a machine learning model to offer suggestions to users using Snap4Arduino (similarly to how iSnap, https://github.com/thomaswp/iSnap, uses logging to obtain data and train a model to assist in block-coding). Thus, we would greatly appreciate it if you could accept these links into the whitelist of websites that can fully utilize Snap4Arduino. If you would like more information about our use case, I would be delighted to provide it. Thank you for your consideration.

### CODE REVIEW

**Comment by bromagosa** [comment]
@jguille2 should we merge this in? :)

**Comment by jguille2** [comment]
Hi Bernat,

Sorry, I have this PR noted on my endless todo list :(

I want to answer @Ericthestein  with more details... Because is not a simple theme.

For me, the idea is not to merge this. Not for anything against it, just because google is not updating any extension... Then, they must to publish that extension... And so, I think it's better to publish its own extension.
It's really easy, but I need to document one or two things (tips about the _key id_). But this will be the most consistent implementation. Their own plugin (with his logo..) to connect their site.

And this will be faster (than merging, waiting for our new release, waiting for Google to publish changes...)
Continue,
Joan

**Comment by Ericthestein** [comment]
@jguille2 and @bromagosa ,

Thank you for the detailed response. My apologies for the long delay; I had been busy with other commitments.

I see your point about creating our own custom TuneScope-Snap4Arduino extension, and I agree that this seems like the best way of going about solving our issue. It would be great if you could provide me with those tips you mentioned before I attempt to publish a fork of this extension. Thank you!

**Comment by jguille2** [comment]
Hi @Ericthestein ,

If you do your own distro, this is very easy for you (much more complicated to build the distro). The _build_ script shows you how this is running... And if you want to build your _crx_ file you have to upload your google _pem_ key file. But I commented the current problems with Chromium extensions... I don't know what's your point (you can't do it without certificate, building only the extension folder)

Anyway, the tips is:
 - [plugin.js](https://github.com/bromagosa/Snap4Arduino/blob/master/src/platforms/web/chromium/root/plugin/plugin.js) must have your extensionId. And your extension ID depends on the way you build it (with _pem_ certificate or not). And you will see it going to `chrome://extensions` after adding it to your browser.

Any extra question, we can continue... but I have not more chrome-google knowledge.

Joan

**Comment by jguille2** [comment]
I close the PR... but we can continue on _issues_ section.

**Pull request closed without merging**
