### PR TITLE
Updated Creative_Robotix library, fixing various issues, adding new blocks.

### PR DESCRIPTION
**Pull request by segertonGH**
Updated Creative_Robotix library, fixed firmata timing issues in blocks (adding a 0.01s exit delay to each block allowing messages to be passed via USB / Bluetooth without corruption, unclear why this fixes the issue).  Added a new line follow block to library.

### CODE REVIEW

**Comment by jguille2** [comment]
Hi @segertonGH 

Yes, sometimes weird things (like adding those "waits")   can solve problems caused between synchronous and asynchronous processes.
Sometimes it is not a good (or robust) solution, because it may depend on the speed... but they can be solutions for most cases.
Other times, they are actually (rather than waiting) adding a "yield" necessary to break a thread's asynchrony.

In this, what you see and what works will be fine.

But there is a mistake. **You have not uploaded the xml of a library but of a project**. I understand that it is a mistake (you want a library, no an example). Then  you have to change the file.

Tell me and we will update our code with the modified library.

Joan

**Comment by segertonGH** [comment]
Hi Joan, 

Thanks, and ops I exported the project instead of just the blocks.  Will correct the pull request.  

All the best,

Simon.

**Comment by segertonGH** [comment]
Hi Joan, 

I believe the pull request is fixed up.  The new update today makes this the final version, and will be stable for a fair while.  Thanks.

Simon.

**Comment by jguille2** [comment]
Hi Simon @segertonGH

Merging your library update, ready for Snap4Arduino9 (I hope it will be released before Christmas)
Thanks

Joan

**Pull request merged**
